name: Parallel jobs
on: push
jobs: # jobs 키에 여러 개의 잡을 정의하면 병렬로 실행된다.
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Third job"
